# Generated by Django 2.0.4 on 2018-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=20)),
                ('rainfall', models.IntegerField(default=0)),
            ],
        ),
    ]
